import { pgTable, text, boolean, integer, timestamp, jsonb } from 'drizzle-orm/pg-core';

// ─── Nomes das tabelas e colunas em português (SQL). ─────────────────────────
// As propriedades TypeScript permanecem em inglês/camelCase para não quebrar
// o código de aplicação. Apenas os nomes SQL (dentro das strings) foram traduzidos.

export const users = pgTable('usuarios', {
  id: text('id').primaryKey(),
  name: text('nome').notNull(),
  login: text('login').notNull().unique(),
  password: text('senha'),
  role: text('perfil').notNull(),
  schoolId: text('autoescola_id'),
  examinerId: text('examinador_id'),
  instructorId: text('instrutor_id'),
  forcePasswordChange: boolean('forcar_troca_senha').default(true),
  allowedModules: jsonb('modulos_permitidos').$type<string[]>().default([]),
  allowedLocationIds: jsonb('locais_permitidos_ids').$type<string[]>().default([]),
  email: text('email'),
  phone: text('telefone'),
  twoFactorEnabled: boolean('dois_fatores_ativo').default(false),
  createdAt: timestamp('criado_em').defaultNow(),
});

export const otpCodes = pgTable('codigos_otp', {
  id: text('id').primaryKey(),
  userId: text('usuario_id').notNull(),
  code: text('codigo').notNull(),        // SHA-256 hash do código real
  expiresAt: timestamp('expira_em').notNull(),
  used: boolean('usado').default(false),
  failedAttempts: integer('tentativas_falhas').default(0),
  createdAt: timestamp('criado_em').defaultNow(),
});

export const drivingSchools = pgTable('autoescolas', {
  id: text('id').primaryKey(),
  name: text('nome').notNull(),
  phone: text('telefone'),
  email: text('email'),
  address: text('endereco'),
  city: text('cidade'),
  services: jsonb('servicos').$type<string[]>().default([]),
  motoYardAddress: text('endereco_patio_moto'),
  carYardAddress: text('endereco_patio_carro'),
  categoryChangeYardAddress: text('endereco_patio_mudanca'),
  mainSchedule: jsonb('banca_principal').$type<any>(),
  provisionalSchedule: jsonb('banca_provisoria').$type<any>(),
  createdAt: timestamp('criado_em').defaultNow(),
});

export const examiners = pgTable('examinadores', {
  id: text('id').primaryKey(),
  name: text('nome').notNull(),
  registrationNumber: text('matricula').notNull(),
  canExamCommon: boolean('pode_examinar_comum').default(true),
  canExamPCD: boolean('pode_examinar_pcd').default(false),
  categories: jsonb('categorias').$type<string[]>().default([]),
  defaultMaxSlotsA: integer('max_vagas_a_padrao'),
  defaultMaxSlotsB: integer('max_vagas_b_padrao'),
  defaultMaxSlotsMudanca: integer('max_vagas_mudanca_padrao'),
  createdAt: timestamp('criado_em').defaultNow(),
});

export const instructors = pgTable('instrutores', {
  id: text('id').primaryKey(),
  name: text('nome').notNull(),
  cpf: text('cpf').notNull(),
  phone: text('telefone'),
  category: text('categoria'),
  plate: text('placa'),
  createdAt: timestamp('criado_em').defaultNow(),
});

export const vehicles = pgTable('veiculos', {
  id: text('id').primaryKey(),
  instructorId: text('instrutor_id').notNull(),
  type: text('tipo').notNull(),
  brand: text('marca').notNull(),
  model: text('modelo').notNull(),
  plate: text('placa').notNull(),
  active: boolean('ativo').default(true),
  transmission: text('transmissao'),
  accessories: jsonb('acessorios').$type<string[]>().default([]),
  duploComando: boolean('duplo_comando').default(false),
  procuracao: boolean('procuracao').default(false),
  createdAt: timestamp('criado_em').defaultNow(),
});

export const examLocations = pgTable('locais_exame', {
  id: text('id').primaryKey(),
  cityId: text('cidade_id').notNull(),
  address: text('endereco'),
  mapsUrl: text('url_maps'),
  regionsServed: jsonb('regioes_atendidas').$type<string[]>().default([]),
  createdAt: timestamp('criado_em').defaultNow(),
});

export const examSchedules = pgTable('bancas', {
  id: text('id').primaryKey(),
  code: text('codigo').unique(),
  date: text('data').notNull(),
  time: text('hora').notNull(),
  examinerIds: jsonb('examinadores_ids').$type<string[]>().default([]),
  maxSlotsA: integer('max_vagas_a').default(10),
  maxSlotsB: integer('max_vagas_b').default(10),
  type: text('tipo').notNull(),
  status: text('status').notNull(),
  cancellationReason: text('motivo_cancelamento'),
  locationId: text('local_id'),
  createdAt: timestamp('criado_em').defaultNow(),
});

export const examRequests = pgTable('solicitacoes', {
  id: text('id').primaryKey(),
  studentName: text('nome_candidato'),
  socialName: text('nome_social'),
  cpf: text('cpf'),
  phone: text('telefone'),
  email: text('email'),
  address: text('endereco'),
  city: text('cidade'),
  requestType: text('tipo_solicitacao').default('EXTRA'),
  examType: text('tipo_exame').notNull(),
  intendedCategory: text('categoria_pretendida').default('B'),
  source: text('origem').notNull(),
  schoolId: text('autoescola_id'),
  paidFee: boolean('taxa_paga_bool').default(false),
  completedPracticalCourse: boolean('curso_pratico_concluido').default(false),
  practicalHours: integer('horas_praticas').default(0),
  hasVehicle: boolean('tem_veiculo').default(false),
  cnhRestriction: text('restricao_cnh'),
  instructor: text('instrutor'),
  vehiclePlate: text('placa_veiculo'),
  semDuploComando: boolean('sem_duplo_comando').default(false),
  checklistVehicle: boolean('checklist_veiculo').default(false),
  practicalCourseInserted: boolean('curso_pratico_inserido').default(false),
  taxaPaga: boolean('taxa_paga').default(false),
  disabilityType: text('tipo_deficiencia'),
  specialNeeds: text('necessidades_especiais'),
  status: text('status').notNull(),
  result: text('resultado'),
  scheduleId: text('banca_id'),
  scheduledDate: text('data_agendada'),
  scheduledTime: text('hora_agendada'),
  scheduledCategory: text('categoria_agendada'),
  examinerId: text('examinador_id'),
  attendanceConfirmed: boolean('presenca_confirmada').default(false),
  cancellationReason: text('motivo_cancelamento'),
  observation: text('observacao'),
  categoryQuantities: jsonb('quantidades_categoria').$type<Record<string, number>>(),
  examHistory: jsonb('historico_exames').default([]),
  modulo: text('modulo'),
  rowColor: text('cor_linha'),
  createdAt: timestamp('criado_em').defaultNow(),
  updatedAt: timestamp('atualizado_em').defaultNow(),
  queueUpdatedAt: timestamp('fila_atualizado_em'),
  scheduledBy: text('agendado_por'),
});

export const systemSettings = pgTable('configuracoes', {
  id: integer('id').primaryKey().default(1),
  agencyName: text('nome_orgao').default('DETRAN'),
  agencyAddress: text('endereco_orgao'),
  logoUrl: text('url_logo'),
  maintenanceMode: boolean('modo_manutencao').default(false),
  minDaysForScheduling: integer('min_dias_agendamento').default(2),
  maxDailySlots: integer('max_vagas_diarias').default(50),
  defaultMaxSlotsA: integer('max_vagas_a_padrao').default(10),
  defaultMaxSlotsB: integer('max_vagas_b_padrao').default(10),
  defaultMaxSlotsMudanca: integer('max_vagas_mudanca_padrao').default(10),
  whatsappMessageTemplate: text('template_whatsapp'),
  cfcWhatsappMessageTemplate: text('template_whatsapp_cfc'),
  defaultExamAddress: text('endereco_exame_padrao'),
  defaultExamAddressLink: text('link_exame_padrao'),
  restrictions: jsonb('restricoes').default([]),
  pcdExamName: text('nome_exame_pcd'),
  pcdDefaultExamAddress: text('endereco_exame_pcd_padrao'),
  pcdDefaultExamAddressLink: text('link_exame_pcd_padrao'),
  pcdMainSchedule: jsonb('banca_principal_pcd'),
  cnhBrasilMainSchedule: jsonb('banca_principal_cnh_brasil'),
  blockWeekends: boolean('bloquear_fins_semana').default(false),
  riskAreaKey: text('chave_area_risco'),
});

export const auditLogs = pgTable('logs_auditoria', {
  id: text('id').primaryKey(),
  userId: text('usuario_id'),
  userName: text('nome_usuario'),
  userRole: text('perfil_usuario'),
  action: text('acao').notNull(),
  entity: text('entidade').notNull(),
  entityId: text('entidade_id'),
  details: jsonb('detalhes').$type<any>(),
  createdAt: timestamp('criado_em').defaultNow(),
});

export const blockedDates = pgTable('datas_bloqueadas', {
  id: text('id').primaryKey(),
  date: text('data').notNull(),
  description: text('descricao'),
  isHoliday: boolean('feriado').default(false),
  createdAt: timestamp('criado_em').defaultNow(),
});

export const cities = pgTable('cidades', {
  id: text('id').primaryKey(),
  name: text('nome').notNull().unique(),
  createdAt: timestamp('criado_em').defaultNow(),
});

export const examScheduleSlots = pgTable('vagas_banca', {
  id: text('id').primaryKey(),
  schoolId: text('autoescola_id').notNull(),
  examType: text('tipo_exame').notNull(),
  requestType: text('tipo_solicitacao').notNull(),
  intendedCategory: text('categoria_pretendida'),
  scheduledDate: text('data_agendada'),
  scheduledTime: text('hora_agendada'),
  examinerId: text('examinador_id'),
  scheduleId: text('banca_id'),
  scheduledCategory: text('categoria_agendada'),
  status: text('status').notNull().default('SCHEDULED'),
  attendanceConfirmed: boolean('presenca_confirmada').default(false),
  cancellationReason: text('motivo_cancelamento'),
  observation: text('observacao'),
  createdAt: timestamp('criado_em').defaultNow(),
  updatedAt: timestamp('atualizado_em').defaultNow(),
});

export const bancaResults = pgTable('resultados_banca', {
  id: text('id').primaryKey(),
  scheduleId: text('banca_id').notNull(),
  schoolId: text('autoescola_id').notNull(),
  category: text('categoria').notNull(),
  totalSlots: integer('total_vagas').default(0),
  usedSlots: integer('vagas_usadas').default(0),
  approved: integer('aprovados').default(0),
  failed: integer('reprovados').default(0),
  absent: integer('ausentes').default(0),
  cancelled: integer('cancelados').default(0),
  modulo: text('modulo'),
  createdAt: timestamp('criado_em').defaultNow(),
  updatedAt: timestamp('atualizado_em').defaultNow(),
});

// ─── Tabelas separadas por módulo ─────────────────────────────────────────────

export const cnhbrasilRequests = pgTable('solicitacoes_cnhbrasil', {
  id: text('id').primaryKey(),
  studentName: text('nome_candidato'),
  socialName: text('nome_social'),
  cpf: text('cpf'),
  phone: text('telefone'),
  email: text('email'),
  address: text('endereco'),
  city: text('cidade'),
  requestType: text('tipo_solicitacao').default('EXTRA'),
  examType: text('tipo_exame').notNull(),
  intendedCategory: text('categoria_pretendida').default('B'),
  source: text('origem').notNull(),
  schoolId: text('autoescola_id'),
  paidFee: boolean('taxa_paga_bool').default(false),
  completedPracticalCourse: boolean('curso_pratico_concluido').default(false),
  practicalHours: integer('horas_praticas').default(0),
  hasVehicle: boolean('tem_veiculo').default(false),
  cnhRestriction: text('restricao_cnh'),
  instructor: text('instrutor'),
  vehiclePlate: text('placa_veiculo'),
  checklistVehicle: boolean('checklist_veiculo').default(false),
  practicalCourseInserted: boolean('curso_pratico_inserido').default(false),
  taxaPaga: boolean('taxa_paga').default(false),
  status: text('status').notNull(),
  result: text('resultado'),
  scheduleId: text('banca_id'),
  scheduledDate: text('data_agendada'),
  scheduledTime: text('hora_agendada'),
  scheduledCategory: text('categoria_agendada'),
  examinerId: text('examinador_id'),
  attendanceConfirmed: boolean('presenca_confirmada').default(false),
  cancellationReason: text('motivo_cancelamento'),
  observation: text('observacao'),
  examHistory: jsonb('historico_exames').default([]),
  modulo: text('modulo'),
  rowColor: text('cor_linha'),
  createdAt: timestamp('criado_em').defaultNow(),
  updatedAt: timestamp('atualizado_em').defaultNow(),
  queueUpdatedAt: timestamp('fila_atualizado_em'),
  scheduledBy: text('agendado_por'),
});

export const cfcRequests = pgTable('solicitacoes_cfc', {
  id: text('id').primaryKey(),
  studentName: text('nome_candidato'),
  socialName: text('nome_social'),
  cpf: text('cpf'),
  phone: text('telefone'),
  email: text('email'),
  address: text('endereco'),
  city: text('cidade'),
  requestType: text('tipo_solicitacao').default('EXTRA'),
  examType: text('tipo_exame').notNull(),
  intendedCategory: text('categoria_pretendida').default('B'),
  source: text('origem').notNull(),
  schoolId: text('autoescola_id'),
  paidFee: boolean('taxa_paga_bool').default(false),
  completedPracticalCourse: boolean('curso_pratico_concluido').default(false),
  practicalHours: integer('horas_praticas').default(0),
  hasVehicle: boolean('tem_veiculo').default(false),
  cnhRestriction: text('restricao_cnh'),
  instructor: text('instrutor'),
  vehiclePlate: text('placa_veiculo'),
  semDuploComando: boolean('sem_duplo_comando').default(false),
  checklistVehicle: boolean('checklist_veiculo').default(false),
  practicalCourseInserted: boolean('curso_pratico_inserido').default(false),
  taxaPaga: boolean('taxa_paga').default(false),
  status: text('status').notNull(),
  result: text('resultado'),
  scheduleId: text('banca_id'),
  scheduledDate: text('data_agendada'),
  scheduledTime: text('hora_agendada'),
  scheduledCategory: text('categoria_agendada'),
  examinerId: text('examinador_id'),
  attendanceConfirmed: boolean('presenca_confirmada').default(false),
  cancellationReason: text('motivo_cancelamento'),
  observation: text('observacao'),
  categoryQuantities: jsonb('quantidades_categoria').$type<Record<string, number>>(),
  examHistory: jsonb('historico_exames').default([]),
  modulo: text('modulo'),
  rowColor: text('cor_linha'),
  createdAt: timestamp('criado_em').defaultNow(),
  updatedAt: timestamp('atualizado_em').defaultNow(),
  queueUpdatedAt: timestamp('fila_atualizado_em'),
  scheduledBy: text('agendado_por'),
});

export const pcdRequests = pgTable('solicitacoes_pcd', {
  id: text('id').primaryKey(),
  studentName: text('nome_candidato'),
  socialName: text('nome_social'),
  cpf: text('cpf'),
  phone: text('telefone'),
  email: text('email'),
  address: text('endereco'),
  city: text('cidade'),
  requestType: text('tipo_solicitacao').default('EXTRA'),
  examType: text('tipo_exame').notNull(),
  intendedCategory: text('categoria_pretendida').default('B'),
  source: text('origem').notNull(),
  schoolId: text('autoescola_id'),
  paidFee: boolean('taxa_paga_bool').default(false),
  completedPracticalCourse: boolean('curso_pratico_concluido').default(false),
  practicalHours: integer('horas_praticas').default(0),
  hasVehicle: boolean('tem_veiculo').default(false),
  cnhRestriction: text('restricao_cnh'),
  instructor: text('instrutor'),
  vehiclePlate: text('placa_veiculo'),
  checklistVehicle: boolean('checklist_veiculo').default(false),
  practicalCourseInserted: boolean('curso_pratico_inserido').default(false),
  taxaPaga: boolean('taxa_paga').default(false),
  disabilityType: text('tipo_deficiencia'),
  specialNeeds: text('necessidades_especiais'),
  status: text('status').notNull(),
  result: text('resultado'),
  scheduleId: text('banca_id'),
  scheduledDate: text('data_agendada'),
  scheduledTime: text('hora_agendada'),
  scheduledCategory: text('categoria_agendada'),
  examinerId: text('examinador_id'),
  attendanceConfirmed: boolean('presenca_confirmada').default(false),
  cancellationReason: text('motivo_cancelamento'),
  observation: text('observacao'),
  examHistory: jsonb('historico_exames').default([]),
  modulo: text('modulo'),
  rowColor: text('cor_linha'),
  createdAt: timestamp('criado_em').defaultNow(),
  updatedAt: timestamp('atualizado_em').defaultNow(),
  queueUpdatedAt: timestamp('fila_atualizado_em'),
  scheduledBy: text('agendado_por'),
});

// ─── Slots de banca por módulo ────────────────────────────────────────────────

export const cfcScheduleSlots = pgTable('vagas_cfc', {
  id: text('id').primaryKey(),
  schoolId: text('autoescola_id').notNull(),
  examType: text('tipo_exame').notNull(),
  requestType: text('tipo_solicitacao').notNull(),
  intendedCategory: text('categoria_pretendida'),
  scheduledDate: text('data_agendada'),
  scheduledTime: text('hora_agendada'),
  examinerId: text('examinador_id'),
  scheduleId: text('banca_id'),
  scheduledCategory: text('categoria_agendada'),
  status: text('status').notNull().default('SCHEDULED'),
  attendanceConfirmed: boolean('presenca_confirmada').default(false),
  cancellationReason: text('motivo_cancelamento'),
  observation: text('observacao'),
  createdAt: timestamp('criado_em').defaultNow(),
  updatedAt: timestamp('atualizado_em').defaultNow(),
});

export const pcdScheduleSlots = pgTable('vagas_pcd', {
  id: text('id').primaryKey(),
  schoolId: text('autoescola_id').notNull(),
  examType: text('tipo_exame').notNull(),
  requestType: text('tipo_solicitacao').notNull(),
  intendedCategory: text('categoria_pretendida'),
  scheduledDate: text('data_agendada'),
  scheduledTime: text('hora_agendada'),
  examinerId: text('examinador_id'),
  scheduleId: text('banca_id'),
  scheduledCategory: text('categoria_agendada'),
  status: text('status').notNull().default('SCHEDULED'),
  attendanceConfirmed: boolean('presenca_confirmada').default(false),
  cancellationReason: text('motivo_cancelamento'),
  observation: text('observacao'),
  createdAt: timestamp('criado_em').defaultNow(),
  updatedAt: timestamp('atualizado_em').defaultNow(),
});
