
import React, { useEffect, useState } from 'react';
import { api } from '../services/api';
import { 
  ExamRequest, 
  ExamType, 
  Examiner, 
  ExamStatus, 
  DrivingSchool,
  User, 
  UserRole,
  RequestType,
  SystemSettings
} from '../types';
import { 
  Plus, 
  Filter, 
  ChevronDown, 
  ChevronUp, 
  AlertTriangle,
  Clock,
  CheckCircle2,
  CheckCircle,
  FileText,
  XCircle,
  Trash2,
  X,
  Save,
  RefreshCw,
  MessageCircle,
  Copy
} from 'lucide-react';

interface CFCSchedulingCenterProps {
  user: User;
}

const CFCSchedulingCenter: React.FC<CFCSchedulingCenterProps> = ({ user }) => {
  const [loading, setLoading] = useState(true);
  const [requests, setRequests] = useState<ExamRequest[]>([]);
  const [schools, setSchools] = useState<DrivingSchool[]>([]);
  const [examiners, setExaminers] = useState<Examiner[]>([]);
  const [systemSettings, setSystemSettings] = useState<SystemSettings | null>(null);
  
  // Expanded sections state
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({
    extras: false,
    waiting: false,
    confirmed: false,
    done: false,
    cancelled: false
  });

  const [expandedDays, setExpandedDays] = useState<Record<string, boolean>>({
    'Segunda-feira': false,
    'Terça-feira': false,
    'Quarta-feira': false,
    'Quinta-feira': false,
    'Sexta-feira': false
  });

  const [expandedWaitingDays, setExpandedWaitingDays] = useState<Record<string, boolean>>({
    'Segunda-feira': false,
    'Terça-feira': false,
    'Quarta-feira': false,
    'Quinta-feira': false,
    'Sexta-feira': false
  });

  // Filters state
  const [filters, setFilters] = useState({
    status: 'ALL',
    schoolId: user.role === UserRole.SCHOOL ? user.schoolId || '' : 'ALL',
    examinerId: 'ALL',
    startDate: '',
    endDate: ''
  });

  // Modal states
  const [isNewModalOpen, setIsNewModalOpen] = useState(false);
  const [isTypeSelectionModalOpen, setIsTypeSelectionModalOpen] = useState(false);
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [isConfirmModalOpen, setIsConfirmModalOpen] = useState(false);
  const [isAutoGenerateModalOpen, setIsAutoGenerateModalOpen] = useState(false);
  const [autoGenerateDate, setAutoGenerateDate] = useState('');
  const [selectedSchoolsForAutoGenerate, setSelectedSchoolsForAutoGenerate] = useState<string[]>([]);
  const [schoolsForAutoGenerate, setSchoolsForAutoGenerate] = useState<DrivingSchool[]>([]);
  const [schoolsWith15Days, setSchoolsWith15Days] = useState<DrivingSchool[]>([]);
  const [isPcdActiveForDay, setIsPcdActiveForDay] = useState(false);
  const [selectedPcdForAutoGenerate, setSelectedPcdForAutoGenerate] = useState(false);
  
  const [confirmConfig, setConfirmConfig] = useState<{
    title: string;
    message: string;
    onConfirm: () => void;
    type: 'blue' | 'red' | 'green';
  } | null>(null);

  const [selectedRequest, setSelectedRequest] = useState<ExamRequest | null>(null);
  const [newRequest, setNewRequest] = useState({
    schoolId: user.role === UserRole.SCHOOL ? user.schoolId || '' : '',
    categories: [] as string[],
    examinerId: '',
    date: '',
    time: '',
    observation: '',
    requestType: RequestType.FIXA
  });

  const fetchData = async () => {
    setLoading(true);
    try {
      const [reqs, schs, exms, settings] = await Promise.all([
        api.getRequests(),
        api.getSchoolsAsync(),
        api.getExaminersAsync(),
        api.getSettings()
      ]);
      
      // Filter for CFC (COMMON and PCD)
      const cfcReqs = reqs.filter(r => r.examType === ExamType.COMMON || r.examType === ExamType.PCD);
      
      setRequests(cfcReqs);
      setSchools(schs);
      setExaminers(exms);
      setSystemSettings(settings);
    } catch (error) {
      console.error('Error fetching data:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const toggleSection = (section: string) => {
    setExpandedSections(prev => ({ ...prev, [section]: !prev[section] }));
  };

  const toggleDay = (day: string) => {
    setExpandedDays(prev => ({ ...prev, [day]: !prev[day] }));
  };

  const toggleWaitingDay = (day: string) => {
    setExpandedWaitingDays(prev => ({ ...prev, [day]: !prev[day] }));
  };

  // Logic to group and filter data
  const filteredRequests = requests.filter(r => {
    if (user.role === UserRole.SCHOOL && r.schoolId !== user.schoolId) return false;
    if (filters.schoolId !== 'ALL' && r.schoolId !== filters.schoolId) return false;
    
    // Status filter logic
    if (filters.status !== 'ALL') {
      if (filters.status === 'WAITING_SCHEDULING') {
        if (r.status !== ExamStatus.WAITING_SCHEDULING) return false;
      } else if (filters.status === 'WAITING_CONFIRMATION') {
        if (r.status !== ExamStatus.SCHEDULED || r.attendanceConfirmed) return false;
      } else if (filters.status === 'CONFIRMED') {
        if (r.status !== ExamStatus.SCHEDULED || !r.attendanceConfirmed) return false;
      } else if (filters.status === 'DONE') {
        if (r.status !== ExamStatus.DONE) return false;
      } else if (filters.status === 'CANCELLED') {
        if (r.status !== ExamStatus.CANCELLED) return false;
      }
    }

    // Date range filter
    if (filters.startDate && r.scheduledDate && r.scheduledDate < filters.startDate) return false;
    if (filters.endDate && r.scheduledDate && r.scheduledDate > filters.endDate) return false;

    // Examiner filter
    if (filters.examinerId !== 'ALL' && r.examinerId !== filters.examinerId) return false;

    return true;
  });

  const extras = filteredRequests
    .filter(r => r.status === ExamStatus.WAITING_SCHEDULING)
    .sort((a, b) => {
      // Reposição first
      if (a.requestType === RequestType.REPOSICAO && b.requestType !== RequestType.REPOSICAO) return -1;
      if (a.requestType !== RequestType.REPOSICAO && b.requestType === RequestType.REPOSICAO) return 1;
      // Then by createdAt (oldest first)
      return new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime();
    });
  const waitingConfirmation = filteredRequests.filter(r => r.status === ExamStatus.SCHEDULED && !r.attendanceConfirmed);
  const confirmed = filteredRequests.filter(r => r.status === ExamStatus.SCHEDULED && r.attendanceConfirmed);
  const done = filteredRequests.filter(r => r.status === ExamStatus.DONE);
  const cancelled = filteredRequests.filter(r => r.status === ExamStatus.CANCELLED);

  // Group confirmed by day of week
  const daysOfWeek = ['Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira'];
  const groupedByDayOfWeek: Record<string, ExamRequest[]> = {
    'Segunda-feira': [],
    'Terça-feira': [],
    'Quarta-feira': [],
    'Quinta-feira': [],
    'Sexta-feira': []
  };

  const groupedWaitingByDayOfWeek: Record<string, ExamRequest[]> = {
    'Segunda-feira': [],
    'Terça-feira': [],
    'Quarta-feira': [],
    'Quinta-feira': [],
    'Sexta-feira': []
  };

  confirmed.forEach(r => {
    if (!r.scheduledDate) return;
    const date = new Date(r.scheduledDate + 'T00:00:00');
    const dayIndex = date.getDay();
    // 0 = Sunday, 1 = Monday, ..., 5 = Friday, 6 = Saturday
    if (dayIndex >= 1 && dayIndex <= 5) {
      const dayName = daysOfWeek[dayIndex - 1];
      groupedByDayOfWeek[dayName].push(r);
    }
  });

  waitingConfirmation.forEach(r => {
    if (!r.scheduledDate) return;
    const date = new Date(r.scheduledDate + 'T00:00:00');
    const dayIndex = date.getDay();
    // 0 = Sunday, 1 = Monday, ..., 5 = Friday, 6 = Saturday
    if (dayIndex >= 1 && dayIndex <= 5) {
      const dayName = daysOfWeek[dayIndex - 1];
      groupedWaitingByDayOfWeek[dayName].push(r);
    }
  });

  const getSchoolName = (id?: string) => {
    if (id === 'PCD') return systemSettings?.pcdExamName || 'Prova Prática PCD';
    return schools.find(s => s.id === id)?.name || 'N/A';
  };
  const getExaminerName = (idOrName?: string) => {
    if (!idOrName) return 'SEM IDENTIFICAÇÃO';
    const examiner = examiners.find(e => e.id === idOrName || e.name === idOrName);
    return examiner ? examiner.name : idOrName;
  };

  const formatDate = (dateStr?: string) => {
    if (!dateStr) return 'Não definida';
    const [year, month, day] = dateStr.split('-');
    return `${day}/${month}/${year}`;
  };

  const getExamTypeLabel = (req: ExamRequest) => {
    if (req.examType === ExamType.PCD) return 'PCD';
    return req.intendedCategory?.split(',').some(c => ['C', 'D', 'E'].includes(c)) 
      ? 'Mudança Categoria' 
      : req.intendedCategory?.split(',').some(c => ['A', 'B'].includes(c))
      ? '1º Habilitação'
      : '-';
  };

  // Sort each day by examiner name and then by time
  daysOfWeek.forEach(day => {
    groupedByDayOfWeek[day].sort((a, b) => {
      const examinerA = getExaminerName(a.examinerId).toUpperCase();
      const examinerB = getExaminerName(b.examinerId).toUpperCase();
      if (examinerA < examinerB) return -1;
      if (examinerA > examinerB) return 1;
      
      const timeA = a.scheduledTime || '00:00';
      const timeB = b.scheduledTime || '00:00';
      return timeA.localeCompare(timeB);
    });

    groupedWaitingByDayOfWeek[day].sort((a, b) => {
      const examinerA = getExaminerName(a.examinerId).toUpperCase();
      const examinerB = getExaminerName(b.examinerId).toUpperCase();
      if (examinerA < examinerB) return -1;
      if (examinerA > examinerB) return 1;
      
      const timeA = a.scheduledTime || '00:00';
      const timeB = b.scheduledTime || '00:00';
      return timeA.localeCompare(timeB);
    });
  });

  const getRequestTypeLabel = (req: ExamRequest) => {
    if (req.requestType === RequestType.REPOSICAO) return 'Reposição';
    if (req.requestType === RequestType.FIXA) return 'Fixa';
    return 'Extra';
  };

  const handleWhatsAppMessage = (req: ExamRequest) => {
    if (!systemSettings?.cfcWhatsappMessageTemplate) {
      alert('Modelo de mensagem WhatsApp não configurado.');
      return;
    }

    const school = schools.find(s => s.id === req.schoolId);
    if (!school || !school.phone) {
      alert('Telefone da autoescola não encontrado.');
      return;
    }

    let message = systemSettings.cfcWhatsappMessageTemplate;
    const examinerName = getExaminerName(req.examinerId);
    const type = req.observation?.includes('Fixa') ? 'Fixa' : 'Extra';
    
    const examType = req.intendedCategory?.includes('C') || req.intendedCategory?.includes('D') || req.intendedCategory?.includes('E') 
      ? 'Mudança Categoria' 
      : '1º Habilitação';
    
    message = message.replace(/{AUTOESCOLA}/g, school.name);
    message = message.replace(/{DATA}/g, formatDate(req.scheduledDate));
    message = message.replace(/{HORARIO}/g, req.scheduledTime || '08:00');
    message = message.replace(/{EXAMINADOR}/g, examinerName);
    message = message.replace(/{EXAME}/g, examType);
    message = message.replace(/{TIPO}/g, type);

    const phone = school.phone.replace(/\D/g, '');
    const finalPhone = phone.startsWith('55') ? phone : `55${phone}`;
    
    const url = `https://wa.me/${finalPhone}?text=${encodeURIComponent(message)}`;
    window.open(url, '_blank');
  };

  const copyDayScheduleToWhatsApp = (dayName: string, dayRequests: ExamRequest[]) => {
    if (dayRequests.length === 0) return;
    
    const firstReq = dayRequests[0];
    const date = new Date(firstReq.scheduledDate + 'T00:00:00');
    const dayOfMonth = date.getDate().toString().padStart(2, '0');
    const months = ['JANEIRO', 'FEVEREIRO', 'MARÇO', 'ABRIL', 'MAIO', 'JUNHO', 'JULHO', 'AGOSTO', 'SETEMBRO', 'OUTUBRO', 'NOVEMBRO', 'DEZEMBRO'];
    const monthName = months[date.getMonth()];
    
    let text = `_*EXAMES PRÁTICOS PARA ${dayName.toUpperCase()} (${dayOfMonth}/${monthName})*_\n\n`;
    
    // Group by examiner
    const byExaminer: Record<string, ExamRequest[]> = {};
    dayRequests.forEach(req => {
      const exName = getExaminerName(req.examinerId).toUpperCase();
      if (!byExaminer[exName]) byExaminer[exName] = [];
      byExaminer[exName].push(req);
    });
    
    // Examiners are already sorted in the dayRequests array
    const sortedExaminerNames = Object.keys(byExaminer).sort();
    
    sortedExaminerNames.forEach(exName => {
      text += `_${exName}_\n`;
      byExaminer[exName].forEach(req => {
        const schoolName = getSchoolName(req.schoolId).toUpperCase();
        const time = req.scheduledTime || '08:00';
        const isMudCat = getExamTypeLabel(req) === 'Mudança Categoria';
        text += `_*${schoolName} - ${time}${isMudCat ? ' (Mud. Cat.)' : ''}*_\n`;
      });
      text += `\n`;
    });
    
    navigator.clipboard.writeText(text.trim());
    alert('Escala copiada para o WhatsApp!');
  };

  const handleConfirmAction = (req: ExamRequest) => {
    setConfirmConfig({
      title: 'Confirmar Agendamento',
      message: 'Tem certeza que deseja confirmar este agendamento?',
      type: 'blue',
      onConfirm: async () => {
        await api.updateRequest(req.id, { attendanceConfirmed: true });
        setIsConfirmModalOpen(false);
        fetchData();
      }
    });
    setIsConfirmModalOpen(true);
  };

  const handleCancelAction = (req: ExamRequest) => {
    setConfirmConfig({
      title: 'Confirmar Cancelado',
      message: "Tem certeza que deseja alterar o status deste agendamento para 'Cancelado'?",
      type: 'red',
      onConfirm: async () => {
        await api.updateRequest(req.id, { status: ExamStatus.CANCELLED });
        setIsConfirmModalOpen(false);
        fetchData();
      }
    });
    setIsConfirmModalOpen(true);
  };

  const handleRealizadoAction = (req: ExamRequest) => {
    setConfirmConfig({
      title: 'Confirmar Realizado',
      message: "Tem certeza que deseja alterar o status deste agendamento para 'Realizado'?",
      type: 'green',
      onConfirm: async () => {
        await api.updateRequest(req.id, { status: ExamStatus.DONE });
        setIsConfirmModalOpen(false);
        fetchData();
      }
    });
    setIsConfirmModalOpen(true);
  };

  useEffect(() => {
    if (autoGenerateDate) {
      const selectedDate = new Date(autoGenerateDate + 'T00:00:00');
      const dayNames = ['DOM', 'SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB'];
      const selectedDayName = dayNames[selectedDate.getDay()];

      const normal: DrivingSchool[] = [];
      const fifteenDays: DrivingSchool[] = [];

      schools.forEach(school => {
        const mainActive = school.mainSchedule?.active;
        const provActive = school.provisionalSchedule?.active;
        const activeSchedule = provActive ? school.provisionalSchedule : (mainActive ? school.mainSchedule : null);

        if (activeSchedule && activeSchedule.days && activeSchedule.days.includes(selectedDayName)) {
          if (activeSchedule.frequency === '15_DAYS') {
            fifteenDays.push(school);
          } else {
            normal.push(school);
          }
        }
      });

      // Check PCD Schedule
      const pcdActive = systemSettings?.pcdMainSchedule?.active;
      const pcdDays = systemSettings?.pcdMainSchedule?.days || [];
      const pcdMatchesDay = pcdActive && pcdDays.includes(selectedDayName);
      setIsPcdActiveForDay(!!pcdMatchesDay);

      setSchoolsForAutoGenerate(normal);
      setSchoolsWith15Days(fifteenDays);
      setSelectedSchoolsForAutoGenerate([...normal.map(s => s.id), ...fifteenDays.map(s => s.id)]);
      setSelectedPcdForAutoGenerate(!!pcdMatchesDay);
    } else {
      setSchoolsForAutoGenerate([]);
      setSchoolsWith15Days([]);
      setSelectedSchoolsForAutoGenerate([]);
      setIsPcdActiveForDay(false);
      setSelectedPcdForAutoGenerate(false);
    }
  }, [autoGenerateDate, schools, systemSettings]);

  const handleAutoGenerate = async () => {
    if (!autoGenerateDate) {
      alert('Por favor, selecione uma data.');
      return;
    }

    if (selectedSchoolsForAutoGenerate.length === 0 && !selectedPcdForAutoGenerate) {
      alert('Por favor, selecione pelo menos uma autoescola ou a prova PCD.');
      return;
    }

    setLoading(true);
    try {
      const selectedDate = new Date(autoGenerateDate + 'T00:00:00');
      const dayNames = ['DOM', 'SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB'];
      const selectedDayName = dayNames[selectedDate.getDay()];

      let count = 0;
      
      // Process Schools
      const schoolsToProcess = schools.filter(s => selectedSchoolsForAutoGenerate.includes(s.id));

      for (const school of schoolsToProcess) {
        // Check which schedule is active
        const mainActive = school.mainSchedule?.active;
        const provActive = school.provisionalSchedule?.active;
        
        // If provisional is active, it overrides main. Otherwise use main.
        const activeSchedule = provActive ? school.provisionalSchedule : (mainActive ? school.mainSchedule : null);
        
        if (activeSchedule && activeSchedule.days && activeSchedule.days.includes(selectedDayName)) {
          // Generate requests for each slot
          const slots = activeSchedule.slots || [];
          for (const slot of slots) {
            // If the slot has a specific day assigned (e.g., in 2_WEEK frequency), only generate if it matches the selected day
            if (slot.day && slot.day !== selectedDayName) {
              continue;
            }

            await api.createRequest({
              schoolId: school.id,
              source: 'SCHOOL',
              examType: ExamType.COMMON,
              intendedCategory: 'A,B', // Default categories for auto-generation
              status: ExamStatus.SCHEDULED,
              attendanceConfirmed: false,
              scheduledDate: autoGenerateDate,
              scheduledTime: slot.time,
              examinerId: slot.examiner,
              observation: 'Escala Fixa'
            });
            count++;
          }
        }
      }

      // Process PCD
      if (selectedPcdForAutoGenerate && systemSettings?.pcdMainSchedule) {
        const pcdSchedule = systemSettings.pcdMainSchedule;
        if (pcdSchedule.active && pcdSchedule.days.includes(selectedDayName)) {
          const slots = pcdSchedule.slots || [];
          for (const slot of slots) {
            if (slot.day && slot.day !== selectedDayName) {
              continue;
            }

            await api.createRequest({
              schoolId: 'PCD',
              source: 'SCHOOL',
              examType: ExamType.PCD,
              intendedCategory: 'B', // PCD is always B
              status: ExamStatus.SCHEDULED,
              attendanceConfirmed: false,
              scheduledDate: autoGenerateDate,
              scheduledTime: slot.time,
              examinerId: slot.examiner,
              observation: 'Escala Fixa'
            });
            count++;
          }
        }
      }

      alert(`${count} agendamentos gerados com sucesso para o dia ${formatDate(autoGenerateDate)}.`);
      setIsAutoGenerateModalOpen(false);
      fetchData();
    } catch (error: any) {
      console.error('Error generating scales:', error);
      const errorMsg = error.message || 'Erro desconhecido';
      alert(`Erro ao gerar escalas automáticas: ${errorMsg}`);
    } finally {
      setLoading(false);
    }
  };

  const handleSubmitNew = async () => {
    const isFixa = newRequest.requestType === RequestType.FIXA;
    const isPcd = newRequest.schoolId === 'PCD';
    const basicFieldsOk = newRequest.schoolId && (isPcd || newRequest.categories.length > 0);
    const fixaFieldsOk = !isFixa || (newRequest.date && newRequest.time && newRequest.examinerId);

    if (!basicFieldsOk || !fixaFieldsOk) {
      alert('Por favor, preencha todos os campos obrigatórios.');
      return;
    }

    try {
      await api.createRequest({
        schoolId: newRequest.schoolId,
        source: 'SCHOOL',
        examType: isPcd ? ExamType.PCD : ExamType.COMMON,
        requestType: newRequest.requestType,
        intendedCategory: isPcd ? 'B' : newRequest.categories.join(','),
        status: newRequest.date ? ExamStatus.SCHEDULED : ExamStatus.WAITING_SCHEDULING,
        attendanceConfirmed: false,
        scheduledDate: newRequest.date,
        scheduledTime: newRequest.time,
        examinerId: newRequest.examinerId,
        observation: newRequest.observation || (newRequest.requestType === RequestType.REPOSICAO ? 'Reposição' : newRequest.requestType === RequestType.FIXA ? 'Escala Fixa' : 'Solicitação Extra')
      });

      setIsNewModalOpen(false);
      setNewRequest({
        schoolId: user.role === UserRole.SCHOOL ? user.schoolId || '' : '',
        categories: [],
        examinerId: '',
        date: '',
        time: '',
        observation: '',
        requestType: RequestType.FIXA
      });
      fetchData();
    } catch (error) {
      console.error('Error creating request:', error);
      alert('Erro ao criar agendamento.');
    }
  };

  const handleCloseNewModal = () => {
    setIsNewModalOpen(false);
    setNewRequest({
      schoolId: user.role === UserRole.SCHOOL ? user.schoolId || '' : '',
      categories: [],
      examinerId: '',
      date: '',
      time: '',
      observation: '',
      requestType: RequestType.FIXA
    });
  };

  const handleUpdateEdit = async () => {
    if (!selectedRequest) return;

    let newStatus = selectedRequest.status;
    // Se for uma solicitação extra pendente e preencher os dados de agendamento, muda para SCHEDULED (Aguardando Confirmação)
    if (selectedRequest.status === ExamStatus.WAITING_SCHEDULING && 
        selectedRequest.scheduledDate && 
        selectedRequest.scheduledTime && 
        selectedRequest.examinerId) {
      newStatus = ExamStatus.SCHEDULED;
    }

    try {
      await api.updateRequest(selectedRequest.id, {
        schoolId: selectedRequest.schoolId,
        intendedCategory: selectedRequest.intendedCategory,
        scheduledDate: selectedRequest.scheduledDate,
        scheduledTime: selectedRequest.scheduledTime,
        examinerId: selectedRequest.examinerId,
        observation: selectedRequest.observation,
        status: newStatus,
        attendanceConfirmed: selectedRequest.attendanceConfirmed
      });
      setIsEditModalOpen(false);
      setSelectedRequest(null);
      fetchData();
    } catch (error) {
      console.error('Error updating request:', error);
      alert('Erro ao atualizar agendamento.');
    }
  };

  const handleDeleteAction = (req: ExamRequest) => {
    setConfirmConfig({
      title: 'Excluir Agendamento',
      message: 'Tem certeza que deseja excluir permanentemente este agendamento?',
      type: 'red',
      onConfirm: async () => {
        await api.deleteRequest(req.id);
        setIsConfirmModalOpen(false);
        fetchData();
      }
    });
    setIsConfirmModalOpen(true);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <RefreshCw className="h-8 w-8 animate-spin text-blue-600" />
      </div>
    );
  }

  return (
    <div className="space-y-6 pb-10">
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Agendamentos</h1>
          <p className="text-slate-500 text-sm">Gerencie os agendamentos de provas práticas</p>
        </div>
        <div className="flex items-center gap-3">
          {user.role !== UserRole.SCHOOL && (
            <button 
              onClick={() => setIsAutoGenerateModalOpen(true)}
              className="bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2 rounded-md flex items-center gap-2 font-bold text-sm shadow-sm transition-colors"
            >
              <RefreshCw className="h-4 w-4" /> Gerar Escalas Fixas Automaticamente
            </button>
          )}
          <button 
            onClick={() => setIsTypeSelectionModalOpen(true)}
            className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md flex items-center gap-2 font-bold text-sm shadow-sm transition-colors"
          >
            <Plus className="h-4 w-4" /> Novo Agendamento
          </button>
        </div>
      </div>

      {/* FILTROS */}
      <div className="bg-white rounded-lg border border-slate-200 shadow-sm overflow-hidden">
        <div className="p-4 border-b border-slate-100 bg-slate-50/50 flex items-center gap-2">
          <Filter className="h-4 w-4 text-slate-400" />
          <h2 className="font-bold text-slate-700 text-sm">Filtros</h2>
        </div>
        <div className="p-5 grid grid-cols-1 md:grid-cols-5 gap-4">
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Status</label>
            <select 
              className="w-full border border-slate-200 rounded-md p-2 text-sm bg-white focus:ring-2 focus:ring-blue-500 outline-none"
              value={filters.status}
              onChange={e => setFilters({...filters, status: e.target.value})}
            >
              <option value="ALL">Todos</option>
              <option value="WAITING_SCHEDULING">Solicitações de Provas Extras</option>
              <option value="WAITING_CONFIRMATION">Aguardando Confirmação</option>
              <option value="CONFIRMED">Provas Confirmadas</option>
              <option value="DONE">Provas Realizadas</option>
              <option value="CANCELLED">Provas Canceladas</option>
            </select>
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Autoescola</label>
            <select 
              className="w-full border border-slate-200 rounded-md p-2 text-sm bg-white focus:ring-2 focus:ring-blue-500 outline-none"
              disabled={user.role === UserRole.SCHOOL}
              value={filters.schoolId}
              onChange={e => setFilters({...filters, schoolId: e.target.value})}
            >
              <option value="ALL">Todas</option>
              {schools.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Examinador</label>
            <select 
              className="w-full border border-slate-200 rounded-md p-2 text-sm bg-white focus:ring-2 focus:ring-blue-500 outline-none"
              value={filters.examinerId}
              onChange={e => setFilters({...filters, examinerId: e.target.value})}
            >
              <option value="ALL">Todos</option>
              {examiners.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}
            </select>
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Data Início</label>
            <input 
              type="date" 
              className="w-full border border-slate-200 rounded-md p-2 text-sm bg-white focus:ring-2 focus:ring-blue-500 outline-none"
              value={filters.startDate}
              onChange={e => setFilters({...filters, startDate: e.target.value})}
            />
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Data Fim</label>
            <input 
              type="date" 
              className="w-full border border-slate-200 rounded-md p-2 text-sm bg-white focus:ring-2 focus:ring-blue-500 outline-none"
              value={filters.endDate}
              onChange={e => setFilters({...filters, endDate: e.target.value})}
            />
          </div>
        </div>
      </div>

      {/* ACCORDIONS */}
      <div className="space-y-4">
        
        {/* SECTION: EXTRAS */}
        <div className="border border-orange-200 rounded-lg overflow-hidden shadow-sm">
          <button 
            onClick={() => toggleSection('extras')}
            className="w-full flex items-center justify-between p-4 bg-orange-50/50 hover:bg-orange-50 transition-colors"
          >
            <div className="flex items-center gap-3 text-orange-700">
              <AlertTriangle className="h-5 w-5" />
              <span className="font-bold">Solicitações de Provas Extras ({extras.length})</span>
            </div>
            {expandedSections.extras ? <ChevronUp className="h-5 w-5 text-orange-400" /> : <ChevronDown className="h-5 w-5 text-orange-400" />}
          </button>
          
          {expandedSections.extras && (
            <div className="p-4 bg-white">
              {extras.length > 0 ? (
                <div className="overflow-x-auto border border-slate-200 rounded-lg">
                  <table className="w-full text-left text-xs">
                    <thead>
                      <tr className="bg-slate-50/50 text-slate-400 uppercase font-bold border-b border-slate-100">
                        <th className="px-4 py-3 text-center">Cadastrado em</th>
                        <th className="px-4 py-3">Tipo</th>
                        <th className="px-4 py-3">Autoescola</th>
                        <th className="px-4 py-3">Exame</th>
                        <th className="px-4 py-3">Observações</th>
                        <th className="px-4 py-3 text-right">Ações</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-50">
                      {extras.map(req => (
                        <tr key={req.id} className="hover:bg-slate-50/30 transition-colors">
                          <td className="px-4 py-3 text-slate-500 text-center">{new Date(req.createdAt).toLocaleString()}</td>
                          <td className="px-4 py-3 text-slate-600">{getRequestTypeLabel(req)}</td>
                          <td className="px-4 py-3 font-black text-slate-800 uppercase">
                            <div className="flex flex-col">
                              {getSchoolName(req.schoolId)}
                              {req.requestType === RequestType.REPOSICAO && (
                                <span className="bg-red-600 text-white text-[9px] font-black px-1.5 py-0.5 rounded w-fit mt-1 uppercase tracking-tighter">
                                  Prioridade
                                </span>
                              )}
                            </div>
                          </td>
                          <td className="px-4 py-3 text-slate-600">
                            {getExamTypeLabel(req)}
                          </td>
                          <td className="px-4 py-3 text-slate-500 max-w-[250px] truncate" title={req.observation}>{req.observation || '-'}</td>
                          <td className="px-4 py-3">
                            <div className="flex items-center justify-end gap-2">
                              {user.role !== UserRole.SCHOOL && (
                                <button 
                                  onClick={() => {
                                    setSelectedRequest(req);
                                    setIsEditModalOpen(true);
                                  }}
                                  className="bg-orange-600 hover:bg-orange-700 text-white px-3 py-1.5 rounded-md flex items-center gap-1.5 font-bold text-[10px] shadow-sm transition-colors"
                                  title="Inserir Dados"
                                >
                                  <FileText className="h-3 w-3" /> Inserir Dados
                                </button>
                              )}
                              <button 
                                onClick={() => handleDeleteAction(req)}
                                className="border border-red-100 text-red-400 hover:text-red-600 hover:bg-red-50 p-2 rounded-md flex items-center justify-center transition-colors"
                                title="Excluir"
                              >
                                <Trash2 className="h-4 w-4" />
                              </button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ) : (
                <p className="text-center py-4 text-slate-400 text-sm italic">Nenhuma solicitação extra pendente.</p>
              )}
            </div>
          )}
        </div>

        {/* SECTION: WAITING CONFIRMATION */}
        <div className="border border-amber-200 rounded-lg overflow-hidden shadow-sm">
          <button 
            onClick={() => toggleSection('waiting')}
            className="w-full flex items-center justify-between p-4 bg-amber-50/50 hover:bg-amber-50 transition-colors"
          >
            <div className="flex items-center gap-3 text-amber-700">
              <Clock className="h-5 w-5" />
              <span className="font-bold">Aguardando Confirmação ({waitingConfirmation.length})</span>
            </div>
            {expandedSections.waiting ? <ChevronUp className="h-5 w-5 text-amber-400" /> : <ChevronDown className="h-5 w-5 text-amber-400" />}
          </button>
          
          {expandedSections.waiting && (
            <div className="p-4 bg-white space-y-4">
              {daysOfWeek.map((dayName) => (
                <div key={dayName} className="border border-slate-200 rounded-lg overflow-hidden">
                  <div className="w-full flex items-center justify-between p-3 bg-slate-50 border-b border-slate-200">
                    <button 
                      onClick={() => toggleWaitingDay(dayName)}
                      className="flex-1 flex items-center justify-between hover:bg-slate-100 transition-colors p-1 rounded"
                    >
                      <span className="font-bold text-slate-700 text-sm uppercase tracking-tight">{dayName} ({groupedWaitingByDayOfWeek[dayName].length})</span>
                      {expandedWaitingDays[dayName] ? <ChevronUp className="h-4 w-4 text-slate-400" /> : <ChevronDown className="h-4 w-4 text-slate-400" />}
                    </button>
                  </div>
                  
                  {expandedWaitingDays[dayName] && (
                    <div className="overflow-x-auto">
                      <table className="w-full text-left text-xs">
                        <thead>
                          <tr className="bg-slate-50/50 text-slate-400 uppercase font-bold border-b border-slate-100">
                            <th className="px-4 py-3">Tipo</th>
                            <th className="px-4 py-3">Autoescola</th>
                            <th className="px-4 py-3">Data</th>
                            <th className="px-4 py-3">Horário</th>
                            <th className="px-4 py-3">Examinador</th>
                            <th className="px-4 py-3">Exame</th>
                            <th className="px-4 py-3 text-right">Ações</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-50">
                          {groupedWaitingByDayOfWeek[dayName].map(req => (
                            <tr key={req.id} className="hover:bg-slate-50/30 transition-colors">
                              <td className="px-4 py-3 text-slate-600">{getRequestTypeLabel(req)}</td>
                              <td className="px-4 py-3 font-black text-slate-800 uppercase">{getSchoolName(req.schoolId)}</td>
                              <td className="px-4 py-3 text-red-600 font-bold">{formatDate(req.scheduledDate)}</td>
                              <td className="px-4 py-3 text-red-600 font-bold">{req.scheduledTime || '08:00'}</td>
                              <td className="px-4 py-3 text-red-600 font-bold uppercase">{getExaminerName(req.examinerId)}</td>
                              <td className="px-4 py-3 text-slate-600">
                                {getExamTypeLabel(req)}
                              </td>
                              <td className="px-4 py-3">
                                <div className="flex items-center justify-end gap-2">
                                  <button 
                                    onClick={() => handleWhatsAppMessage(req)}
                                    className="bg-emerald-500 hover:bg-emerald-600 text-white p-2 rounded-md flex items-center justify-center shadow-sm transition-colors"
                                    title="Enviar WhatsApp"
                                  >
                                    <MessageCircle className="h-4 w-4" />
                                  </button>
                                  <button 
                                    onClick={() => handleConfirmAction(req)}
                                    className="bg-green-600 hover:bg-green-700 text-white p-2 rounded-md flex items-center justify-center shadow-sm transition-colors"
                                    title="Confirmar"
                                  >
                                    <CheckCircle className="h-4 w-4" />
                                  </button>
                                  <button 
                                    onClick={() => handleCancelAction(req)}
                                    className="border border-red-200 text-red-600 hover:bg-red-50 p-2 rounded-md flex items-center justify-center transition-colors"
                                    title="Cancelar"
                                  >
                                    <XCircle className="h-4 w-4" />
                                  </button>
                                </div>
                              </td>
                            </tr>
                          ))}
                          {groupedWaitingByDayOfWeek[dayName].length === 0 && (
                            <tr>
                              <td colSpan={7} className="px-4 py-8 text-center text-slate-400 italic">Nenhum agendamento para este dia.</td>
                            </tr>
                          )}
                        </tbody>
                      </table>
                    </div>
                  )}
                </div>
              ))}
              {waitingConfirmation.length === 0 && <p className="text-center py-4 text-slate-400 text-sm italic">Nenhum agendamento aguardando confirmação.</p>}
            </div>
          )}
        </div>

        {/* SECTION: CONFIRMED */}
        <div className="border border-green-200 rounded-lg overflow-hidden shadow-sm">
          <button 
            onClick={() => toggleSection('confirmed')}
            className="w-full flex items-center justify-between p-4 bg-green-50/50 hover:bg-green-50 transition-colors"
          >
            <div className="flex items-center gap-3 text-green-700">
              <CheckCircle2 className="h-5 w-5" />
              <span className="font-bold">Provas Confirmadas ({confirmed.length})</span>
            </div>
            {expandedSections.confirmed ? <ChevronUp className="h-5 w-5 text-green-400" /> : <ChevronDown className="h-5 w-5 text-green-400" />}
          </button>
          
          {expandedSections.confirmed && (
            <div className="p-4 bg-white space-y-4">
              {daysOfWeek.map((dayName) => (
                <div key={dayName} className="border border-slate-200 rounded-lg overflow-hidden">
                  <div className="w-full flex items-center justify-between p-3 bg-slate-50 border-b border-slate-200">
                    <button 
                      onClick={() => toggleDay(dayName)}
                      className="flex-1 flex items-center justify-between hover:bg-slate-100 transition-colors p-1 rounded"
                    >
                      <span className="font-bold text-slate-700 text-sm uppercase tracking-tight">{dayName} ({groupedByDayOfWeek[dayName].length})</span>
                      {expandedDays[dayName] ? <ChevronUp className="h-4 w-4 text-slate-400" /> : <ChevronDown className="h-4 w-4 text-slate-400" />}
                    </button>
                    {groupedByDayOfWeek[dayName].length > 0 && (
                      <button 
                        onClick={(e) => {
                          e.stopPropagation();
                          copyDayScheduleToWhatsApp(dayName, groupedByDayOfWeek[dayName]);
                        }}
                        className="ml-2 p-1.5 text-emerald-600 hover:bg-emerald-50 rounded-md transition-colors"
                        title="Copiar Escala para WhatsApp"
                      >
                        <Copy className="h-4 w-4" />
                      </button>
                    )}
                  </div>
                  
                  {expandedDays[dayName] && (
                    <div className="overflow-x-auto">
                      <table className="w-full text-left text-xs">
                        <thead>
                          <tr className="bg-slate-50/50 text-slate-400 uppercase font-bold border-b border-slate-100">
                            <th className="px-4 py-3">Tipo</th>
                            <th className="px-4 py-3">Autoescola</th>
                            <th className="px-4 py-3">Data</th>
                            <th className="px-4 py-3">Horário</th>
                            <th className="px-4 py-3">Examinador</th>
                            <th className="px-4 py-3">Exame</th>
                            <th className="px-4 py-3">Ações</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-50">
                          {groupedByDayOfWeek[dayName].map(req => (
                            <tr key={req.id} className="hover:bg-slate-50/30 transition-colors">
                              <td className="px-4 py-3 text-slate-600">{getRequestTypeLabel(req)}</td>
                              <td className="px-4 py-3 font-black text-slate-800 uppercase">{getSchoolName(req.schoolId)}</td>
                              <td className="px-4 py-3 text-slate-600">{formatDate(req.scheduledDate)}</td>
                              <td className="px-4 py-3 text-slate-600">{req.scheduledTime || '08:00'}</td>
                              <td className="px-4 py-3 text-slate-600 uppercase">{getExaminerName(req.examinerId)}</td>
                              <td className="px-4 py-3 text-slate-600">
                                {getExamTypeLabel(req)}
                              </td>
                              <td className="px-4 py-3">
                                <div className="flex items-center gap-2">
                                  <button 
                                    onClick={() => handleRealizadoAction(req)}
                                    className="bg-green-600 hover:bg-green-700 text-white px-3 py-1.5 rounded-md flex items-center gap-1.5 font-bold text-[10px] shadow-sm transition-colors"
                                  >
                                    <CheckCircle className="h-3 w-3" /> Realizado
                                  </button>
                                  <button 
                                    onClick={() => handleCancelAction(req)}
                                    className="border border-red-200 text-red-600 hover:bg-red-50 px-3 py-1.5 rounded-md flex items-center gap-1.5 font-bold text-[10px] transition-colors"
                                  >
                                    <XCircle className="h-3 w-3" /> Cancelar
                                  </button>
                                </div>
                              </td>
                            </tr>
                          ))}
                          {groupedByDayOfWeek[dayName].length === 0 && (
                            <tr>
                              <td colSpan={7} className="px-4 py-8 text-center text-slate-400 italic">Nenhum agendamento para este dia.</td>
                            </tr>
                          )}
                        </tbody>
                      </table>
                    </div>
                  )}
                </div>
              ))}
              {confirmed.length === 0 && <p className="text-center py-4 text-slate-400 text-sm italic">Nenhum agendamento confirmado.</p>}
            </div>
          )}
        </div>

        {/* SECTION: DONE */}
        <div className="border border-blue-200 rounded-lg overflow-hidden shadow-sm">
          <button 
            onClick={() => toggleSection('done')}
            className="w-full flex items-center justify-between p-4 bg-blue-50/50 hover:bg-blue-50 transition-colors"
          >
            <div className="flex items-center gap-3 text-blue-700">
              <CheckCircle2 className="h-5 w-5" />
              <span className="font-bold">Provas Realizadas ({done.length})</span>
            </div>
            {expandedSections.done ? <ChevronUp className="h-5 w-5 text-blue-400" /> : <ChevronDown className="h-5 w-5 text-blue-400" />}
          </button>
          {expandedSections.done && (
            <div className="p-4 bg-white">
               {done.length > 0 ? (
                 <div className="overflow-x-auto">
                   <table className="w-full text-left text-xs">
                     <thead>
                       <tr className="border-b border-slate-100 text-slate-400 uppercase font-bold tracking-wider">
                         <th className="px-4 py-3">Tipo</th>
                         <th className="px-4 py-3">Autoescola</th>
                         <th className="px-4 py-3">Data</th>
                         <th className="px-4 py-3">Horário</th>
                         <th className="px-4 py-3">Examinador</th>
                         <th className="px-4 py-3">Exame</th>
                       </tr>
                     </thead>
                     <tbody className="divide-y divide-slate-50">
                       {done.map(req => (
                         <tr key={req.id} className="hover:bg-slate-50/30 transition-colors">
                           <td className="px-4 py-3 text-slate-600">{getRequestTypeLabel(req)}</td>
                           <td className="px-4 py-3 font-black text-slate-800 uppercase">{getSchoolName(req.schoolId)}</td>
                           <td className="px-4 py-3 text-slate-600">{formatDate(req.scheduledDate)}</td>
                           <td className="px-4 py-3 text-slate-600">{req.scheduledTime || '08:00'}</td>
                           <td className="px-4 py-3 text-slate-600 uppercase">{getExaminerName(req.examinerId)}</td>
                           <td className="px-4 py-3 text-slate-600">{getExamTypeLabel(req)}</td>
                         </tr>
                       ))}
                     </tbody>
                   </table>
                 </div>
               ) : (
                 <p className="text-center py-4 text-slate-400 text-sm italic">Nenhuma prova realizada encontrada.</p>
               )}
            </div>
          )}
        </div>

        {/* SECTION: CANCELLED */}
        <div className="border border-red-200 rounded-lg overflow-hidden shadow-sm">
          <button 
            onClick={() => toggleSection('cancelled')}
            className="w-full flex items-center justify-between p-4 bg-red-50/50 hover:bg-red-50 transition-colors"
          >
            <div className="flex items-center gap-3 text-red-700">
              <XCircle className="h-5 w-5" />
              <span className="font-bold">Provas Canceladas ({cancelled.length})</span>
            </div>
            {expandedSections.cancelled ? <ChevronUp className="h-5 w-5 text-red-400" /> : <ChevronDown className="h-5 w-5 text-red-400" />}
          </button>
          {expandedSections.cancelled && (
            <div className="p-4 bg-white">
               {cancelled.length > 0 ? (
                 <div className="overflow-x-auto">
                   <table className="w-full text-left text-xs">
                     <thead>
                       <tr className="border-b border-slate-100 text-slate-400 uppercase font-bold tracking-wider">
                         <th className="px-4 py-3">Tipo</th>
                         <th className="px-4 py-3">Autoescola</th>
                         <th className="px-4 py-3">Data</th>
                         <th className="px-4 py-3">Horário</th>
                         <th className="px-4 py-3">Examinador</th>
                         <th className="px-4 py-3">Exame</th>
                       </tr>
                     </thead>
                     <tbody className="divide-y divide-slate-50">
                       {cancelled.map(req => (
                         <tr key={req.id} className="hover:bg-slate-50/30 transition-colors">
                           <td className="px-4 py-3 text-slate-600">{getRequestTypeLabel(req)}</td>
                           <td className="px-4 py-3 font-black text-slate-800 uppercase">{getSchoolName(req.schoolId)}</td>
                           <td className="px-4 py-3 text-slate-600">{formatDate(req.scheduledDate)}</td>
                           <td className="px-4 py-3 text-slate-600">{req.scheduledTime || '08:00'}</td>
                           <td className="px-4 py-3 text-slate-600 uppercase">{getExaminerName(req.examinerId)}</td>
                           <td className="px-4 py-3 text-slate-600">{getExamTypeLabel(req)}</td>
                         </tr>
                       ))}
                     </tbody>
                   </table>
                 </div>
               ) : (
                 <p className="text-center py-4 text-slate-400 text-sm italic">Nenhuma prova cancelada encontrada.</p>
               )}
            </div>
          )}
        </div>

      </div>

      {/* MODAL: GERAR ESCALAS AUTOMATICAMENTE */}
      {isAutoGenerateModalOpen && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg overflow-hidden animate-in fade-in zoom-in duration-200">
            <div className="flex justify-between items-center p-6 border-b border-slate-100">
              <h2 className="text-xl font-bold text-slate-800">Gerar Escalas Automáticas</h2>
              <button onClick={() => setIsAutoGenerateModalOpen(false)} className="text-slate-400 hover:text-slate-600 transition-colors">
                <X className="h-6 w-6" />
              </button>
            </div>
            
            <div className="p-6 space-y-4 max-h-[70vh] overflow-y-auto">
              <p className="text-sm text-slate-600">
                Selecione a data para a qual deseja gerar as escalas fixas. O sistema irá buscar a configuração ativa (Principal ou Provisória) de cada autoescola para este dia da semana.
              </p>
              
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Data Selecionada <span className="text-red-500">*</span></label>
                <input 
                  type="date" 
                  className="w-full border border-slate-200 rounded-lg p-2.5 text-sm bg-slate-50 focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                  value={autoGenerateDate}
                  onChange={e => setAutoGenerateDate(e.target.value)}
                />
              </div>

              {autoGenerateDate && (
                <div className="space-y-6 pt-2">
                  {/* List 1: Normal Schedules */}
                  <div className="space-y-3">
                    <h3 className="text-xs font-black text-slate-400 uppercase tracking-widest border-b border-slate-100 pb-1">Autoescolas do Dia (Escala Normal)</h3>
                    
                    {/* PCD Option */}
                    {isPcdActiveForDay && (
                      <label className="flex items-center gap-3 p-2 hover:bg-blue-50 rounded-md cursor-pointer transition-colors border border-transparent hover:border-blue-100 bg-blue-50/30">
                        <input 
                          type="checkbox" 
                          className="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
                          checked={selectedPcdForAutoGenerate}
                          onChange={e => setSelectedPcdForAutoGenerate(e.target.checked)}
                        />
                        <div className="flex flex-col">
                          <span className="text-sm font-bold text-blue-700">{systemSettings?.pcdExamName || 'Prova Prática PCD'}</span>
                          <span className="text-[10px] text-blue-500 font-bold uppercase">Configuração Global PCD</span>
                        </div>
                      </label>
                    )}

                    {schoolsForAutoGenerate.length > 0 ? (
                      <div className="grid grid-cols-1 gap-2">
                        {schoolsForAutoGenerate.map(school => (
                          <label key={school.id} className="flex items-center gap-3 p-2 hover:bg-slate-50 rounded-md cursor-pointer transition-colors border border-transparent hover:border-slate-100">
                            <input 
                              type="checkbox" 
                              className="h-4 w-4 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500"
                              checked={selectedSchoolsForAutoGenerate.includes(school.id)}
                              onChange={e => {
                                if (e.target.checked) {
                                  setSelectedSchoolsForAutoGenerate([...selectedSchoolsForAutoGenerate, school.id]);
                                } else {
                                  setSelectedSchoolsForAutoGenerate(selectedSchoolsForAutoGenerate.filter(id => id !== school.id));
                                }
                              }}
                            />
                            <span className="text-sm font-bold text-slate-700">{school.name}</span>
                          </label>
                        ))}
                      </div>
                    ) : (
                      <p className="text-xs text-slate-400 italic">Nenhuma autoescola configurada para este dia.</p>
                    )}
                  </div>

                  {/* List 2: 15-Day Schedules */}
                  <div className="space-y-3">
                    <h3 className="text-xs font-black text-slate-400 uppercase tracking-widest border-b border-slate-100 pb-1">Autoescolas a cada 15 dias</h3>
                    {schoolsWith15Days.length > 0 ? (
                      <div className="grid grid-cols-1 gap-2">
                        {schoolsWith15Days.map(school => (
                          <label key={school.id} className="flex items-center gap-3 p-2 hover:bg-slate-50 rounded-md cursor-pointer transition-colors border border-transparent hover:border-slate-100">
                            <input 
                              type="checkbox" 
                              className="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
                              checked={selectedSchoolsForAutoGenerate.includes(school.id)}
                              onChange={e => {
                                if (e.target.checked) {
                                  setSelectedSchoolsForAutoGenerate([...selectedSchoolsForAutoGenerate, school.id]);
                                } else {
                                  setSelectedSchoolsForAutoGenerate(selectedSchoolsForAutoGenerate.filter(id => id !== school.id));
                                }
                              }}
                            />
                            <div className="flex flex-col">
                              <span className="text-sm font-bold text-slate-700">{school.name}</span>
                              <span className="text-[10px] text-blue-600 font-bold uppercase">Escala Quinzenal (Desmarque para inverter)</span>
                            </div>
                          </label>
                        ))}
                      </div>
                    ) : (
                      <p className="text-xs text-slate-400 italic">Nenhuma autoescola com escala de 15 dias para este dia.</p>
                    )}
                  </div>
                </div>
              )}
            </div>

            <div className="p-6 bg-slate-50 border-t border-slate-100 flex justify-end gap-3">
              <button 
                onClick={() => setIsAutoGenerateModalOpen(false)}
                className="px-6 py-2 rounded-lg border border-slate-200 text-slate-600 font-bold text-sm hover:bg-white transition-all"
              >
                Cancelar
              </button>
              <button 
                onClick={handleAutoGenerate}
                className="px-8 py-2 rounded-lg bg-emerald-600 text-white font-bold text-sm hover:bg-emerald-700 shadow-md shadow-emerald-200 transition-all flex items-center gap-2"
              >
                <RefreshCw className="h-4 w-4" /> Gerar Escalas
              </button>
            </div>
          </div>
        </div>
      )}

      {/* MODAL: SELEÇÃO DE TIPO DE AGENDAMENTO */}
      {isTypeSelectionModalOpen && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-sm overflow-hidden animate-in fade-in zoom-in duration-200">
            <div className="p-6 border-b border-slate-100">
              <h2 className="text-lg font-bold text-slate-800">Tipo de Agendamento</h2>
            </div>
            <div className="p-6 grid grid-cols-3 gap-4">
              <button 
                onClick={() => {
                  setNewRequest({...newRequest, requestType: RequestType.FIXA});
                  setIsTypeSelectionModalOpen(false);
                  setIsNewModalOpen(true);
                }}
                className="bg-blue-100 hover:bg-blue-200 text-blue-800 font-bold py-4 rounded-lg transition-all"
              >
                Fixo
              </button>
              <button 
                onClick={() => {
                  setNewRequest({...newRequest, requestType: RequestType.EXTRA});
                  setIsTypeSelectionModalOpen(false);
                  setIsNewModalOpen(true);
                }}
                className="bg-orange-100 hover:bg-orange-200 text-orange-800 font-bold py-4 rounded-lg transition-all"
              >
                Extra
              </button>
              <button 
                onClick={() => {
                  setNewRequest({...newRequest, requestType: RequestType.REPOSICAO});
                  setIsTypeSelectionModalOpen(false);
                  setIsNewModalOpen(true);
                }}
                className="bg-emerald-100 hover:bg-emerald-200 text-emerald-800 font-bold py-4 rounded-lg transition-all"
              >
                Reposição
              </button>
            </div>
            <div className="p-4 bg-slate-50 border-t border-slate-100 flex justify-end">
              <button 
                onClick={() => {
                  setIsTypeSelectionModalOpen(false);
                  setNewRequest({
                    schoolId: user.role === UserRole.SCHOOL ? user.schoolId || '' : '',
                    categories: [],
                    examinerId: '',
                    date: '',
                    time: '',
                    observation: '',
                    requestType: RequestType.FIXA
                  });
                }}
                className="px-4 py-2 rounded-lg text-sm font-bold text-slate-600 hover:bg-slate-200 transition-all"
              >
                Cancelar
              </button>
            </div>
          </div>
        </div>
      )}

      {/* MODAL: NOVO AGENDAMENTO */}
      {isNewModalOpen && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl overflow-hidden animate-in fade-in zoom-in duration-200">
            <div className="flex justify-between items-center p-6 border-b border-slate-100">
              <h2 className="text-xl font-bold text-slate-800">Novo Agendamento</h2>
              <button onClick={handleCloseNewModal} className="text-slate-400 hover:text-slate-600 transition-colors">
                <X className="h-6 w-6" />
              </button>
            </div>
            
            <div className="p-6 space-y-6">
              <div className="bg-red-50 border border-red-100 rounded-lg p-4 text-center">
                <p className="text-red-600 font-bold text-sm">Atenção: O número máximo será de 10 vagas por Categoria!</p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Autoescola <span className="text-red-500">*</span></label>
                  <select 
                    className="w-full border border-slate-200 rounded-lg p-2.5 text-sm bg-slate-50 focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                    value={newRequest.schoolId}
                    onChange={e => setNewRequest({...newRequest, schoolId: e.target.value, categories: []})}
                    disabled={user.role === UserRole.SCHOOL}
                  >
                    <option value="">Selecione a autoescola</option>
                    {schools.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                    {user.role !== UserRole.SCHOOL && (
                      <option value="PCD">{systemSettings?.pcdExamName || 'Prova Prática PCD'}</option>
                    )}
                  </select>
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Categoria <span className="text-red-500">*</span></label>
                  <div className="flex items-center gap-4 pt-2">
                    {newRequest.schoolId === 'PCD' ? (
                      <label className="flex items-center gap-2 cursor-pointer group">
                        <input 
                          type="checkbox" 
                          className="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500" 
                          checked={true}
                          readOnly
                        />
                        <span className="text-sm font-bold text-slate-700 group-hover:text-blue-600 transition-colors">B (PCD)</span>
                      </label>
                    ) : (
                      (newRequest.schoolId 
                        ? schools.find(s => s.id === newRequest.schoolId)?.services || [] 
                        : ['A', 'B', 'C', 'D', 'E', 'PCD']
                      ).filter(cat => {
                        if (newRequest.requestType === RequestType.FIXA || newRequest.requestType === RequestType.REPOSICAO) {
                          return ['A', 'B'].includes(cat);
                        }
                        return true;
                      }).map(cat => (
                        <label key={cat} className="flex items-center gap-2 cursor-pointer group">
                          <input 
                            type="checkbox" 
                            className="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500" 
                            checked={newRequest.categories.includes(cat)}
                            onChange={e => {
                              let newCats = e.target.checked 
                                ? [...newRequest.categories, cat]
                                : newRequest.categories.filter(c => c !== cat);
                              
                              // Regra: Não permitir A/B junto com C/D/E
                              const hasAB = newCats.some(c => ['A', 'B'].includes(c));
                              const hasCDE = newCats.some(c => ['C', 'D', 'E'].includes(c));
                              if (hasAB && hasCDE) {
                                alert('Não é permitido selecionar categorias A/B junto com C/D/E.');
                                return;
                              }
                              
                              setNewRequest({...newRequest, categories: newCats});
                            }}
                          />
                          <span className="text-sm font-bold text-slate-700 group-hover:text-blue-600 transition-colors">{cat}</span>
                        </label>
                      ))
                    )}
                  </div>
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Exame <span className="text-red-500">*</span></label>
                  <input 
                    type="text" 
                    value={
                      newRequest.schoolId === 'PCD'
                        ? 'PCD'
                        : newRequest.categories.some(c => ['A', 'B'].includes(c)) && !newRequest.categories.some(c => ['C', 'D', 'E'].includes(c))
                        ? '1º Habilitação'
                        : newRequest.categories.some(c => ['C', 'D', 'E'].includes(c))
                        ? 'Mudança Categoria'
                        : ''
                    }
                    readOnly
                    className="w-full border border-slate-200 rounded-lg p-2.5 text-sm bg-slate-100 text-slate-500 outline-none"
                  />
                </div>

                {newRequest.requestType === RequestType.FIXA && (
                  <>
                    <div className="space-y-1.5">
                      <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Examinador <span className="text-red-500">*</span></label>
                      <select 
                        className="w-full border border-slate-200 rounded-lg p-2.5 text-sm bg-slate-50 focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                        value={newRequest.examinerId}
                        onChange={e => setNewRequest({...newRequest, examinerId: e.target.value})}
                      >
                        <option value="">Selecione o examinador</option>
                        {examiners.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}
                      </select>
                    </div>

                    <div className="space-y-1.5">
                      <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Data <span className="text-red-500">*</span></label>
                      <input 
                        type="date" 
                        className="w-full border border-slate-200 rounded-lg p-2.5 text-sm bg-slate-50 focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                        value={newRequest.date}
                        onChange={e => setNewRequest({...newRequest, date: e.target.value})}
                      />
                    </div>

                    <div className="space-y-1.5">
                      <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Horário <span className="text-red-500">*</span></label>
                      <input 
                        type="time" 
                        className="w-full border border-slate-200 rounded-lg p-2.5 text-sm bg-slate-50 focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                        value={newRequest.time}
                        onChange={e => setNewRequest({...newRequest, time: e.target.value})}
                      />
                    </div>
                  </>
                )}
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Observações</label>
                <textarea 
                  rows={3}
                  placeholder="Observações adicionais..."
                  className="w-full border border-slate-200 rounded-lg p-2.5 text-sm bg-slate-50 focus:ring-2 focus:ring-blue-500 outline-none transition-all resize-none"
                  value={newRequest.observation}
                  onChange={e => setNewRequest({...newRequest, observation: e.target.value})}
                ></textarea>
              </div>
            </div>

            <div className="p-6 bg-slate-50 border-t border-slate-100 flex justify-end gap-3">
              <button 
                onClick={handleCloseNewModal}
                className="px-6 py-2 rounded-lg border border-slate-200 text-slate-600 font-bold text-sm hover:bg-white transition-all"
              >
                Cancelar
              </button>
              <button 
                onClick={handleSubmitNew}
                className="px-8 py-2 rounded-lg bg-blue-600 text-white font-bold text-sm hover:bg-blue-700 shadow-md shadow-blue-200 transition-all flex items-center gap-2"
              >
                <Save className="h-4 w-4" /> Salvar
              </button>
            </div>
          </div>
        </div>
      )}

      {/* MODAL: EDITAR AGENDAMENTO */}
      {isEditModalOpen && selectedRequest && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl overflow-hidden animate-in fade-in zoom-in duration-200">
            <div className="flex justify-between items-center p-6 border-b border-slate-100">
              <h2 className="text-xl font-bold text-slate-800">Editar Agendamento</h2>
              <button onClick={() => setIsEditModalOpen(false)} className="text-slate-400 hover:text-slate-600 transition-colors">
                <X className="h-6 w-6" />
              </button>
            </div>
            
            <div className="p-6 space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="md:col-span-2 space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Autoescola</label>
                  <select 
                    className="w-full border border-slate-200 rounded-lg p-2.5 text-sm bg-slate-50 focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                    value={selectedRequest.schoolId}
                    onChange={e => setSelectedRequest({...selectedRequest, schoolId: e.target.value})}
                    disabled={user.role === UserRole.SCHOOL}
                  >
                    {schools.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                  </select>
                </div>

                <div className="md:col-span-2 space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Categoria <span className="text-red-500">*</span></label>
                  <div className="flex flex-wrap items-center gap-6 p-3 bg-slate-50 rounded-lg border border-slate-100">
                    {(selectedRequest.schoolId 
                      ? schools.find(s => s.id === selectedRequest.schoolId)?.services || [] 
                      : ['A', 'B', 'C', 'D', 'E', 'PCD']
                    ).filter(cat => {
                      if (selectedRequest.requestType === RequestType.FIXA || selectedRequest.requestType === RequestType.REPOSICAO) {
                        return ['A', 'B'].includes(cat);
                      }
                      return true;
                    }).map(cat => (
                      <label key={cat} className="flex items-center gap-2 cursor-pointer group">
                        <input 
                          type="checkbox" 
                          className="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500" 
                          checked={selectedRequest.intendedCategory?.split(',').includes(cat)}
                          onChange={e => {
                            const currentCats = selectedRequest.intendedCategory ? selectedRequest.intendedCategory.split(',').filter(Boolean) : [];
                            let newCats = e.target.checked 
                              ? [...currentCats, cat]
                              : currentCats.filter(c => c !== cat);
                            
                            // Regra: Não permitir A/B junto com C/D/E
                            const hasAB = newCats.some(c => ['A', 'B'].includes(c));
                            const hasCDE = newCats.some(c => ['C', 'D', 'E'].includes(c));
                            if (hasAB && hasCDE) {
                              alert('Não é permitido selecionar categorias A/B junto com C/D/E.');
                              return;
                            }
                            
                            setSelectedRequest({...selectedRequest, intendedCategory: newCats.join(',')});
                          }}
                        />
                        <span className="text-sm font-bold text-slate-700 group-hover:text-blue-600 transition-colors">{cat}</span>
                      </label>
                    ))}
                  </div>
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Exame</label>
                  <div className="w-full border border-slate-200 rounded-lg p-2.5 text-sm bg-slate-100 text-slate-600 font-bold">
                    {getExamTypeLabel(selectedRequest)}
                  </div>
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Data</label>
                  <input 
                    type="date" 
                    className="w-full border border-slate-200 rounded-lg p-2.5 text-sm bg-slate-50 focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                    value={selectedRequest.scheduledDate || ''}
                    onChange={e => setSelectedRequest({...selectedRequest, scheduledDate: e.target.value})}
                  />
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Horário</label>
                  <input 
                    type="time" 
                    className="w-full border border-slate-200 rounded-lg p-2.5 text-sm bg-slate-50 focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                    value={selectedRequest.scheduledTime || ''}
                    onChange={e => setSelectedRequest({...selectedRequest, scheduledTime: e.target.value})}
                  />
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Examinador</label>
                  <select 
                    className="w-full border border-slate-200 rounded-lg p-2.5 text-sm bg-slate-50 focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                    value={selectedRequest.examinerId || ''}
                    onChange={e => setSelectedRequest({...selectedRequest, examinerId: e.target.value})}
                  >
                    <option value="">Selecione o examinador</option>
                    {examiners.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}
                  </select>
                </div>
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Observações</label>
                <textarea 
                  rows={3}
                  className="w-full border border-slate-200 rounded-lg p-2.5 text-sm bg-slate-50 focus:ring-2 focus:ring-blue-500 outline-none transition-all resize-none"
                  placeholder="Observações adicionais..."
                  value={selectedRequest.observation || ''}
                  onChange={e => setSelectedRequest({...selectedRequest, observation: e.target.value})}
                ></textarea>
              </div>
            </div>

            <div className="p-6 border-t border-slate-100 bg-slate-50 flex justify-end items-center">
              <div className="flex gap-3">
                <button 
                  onClick={() => setIsEditModalOpen(false)}
                  className="px-6 py-2.5 rounded-lg text-sm font-bold text-slate-600 hover:bg-slate-200 transition-colors"
                >
                  Cancelar
                </button>
                <button 
                  onClick={handleUpdateEdit}
                  className="px-6 py-2.5 rounded-lg text-sm font-bold text-white bg-blue-600 hover:bg-blue-700 shadow-lg shadow-blue-200 transition-all flex items-center gap-2"
                >
                  <Save className="h-4 w-4" /> Atualizar
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* CONFIRMATION MODAL */}
      {isConfirmModalOpen && confirmConfig && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[60] flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-md overflow-hidden animate-in fade-in zoom-in duration-200">
            <div className="p-8 text-center space-y-4">
              <div className={`mx-auto h-16 w-16 rounded-full flex items-center justify-center ${
                confirmConfig.type === 'blue' ? 'bg-blue-50 text-blue-600' : 
                confirmConfig.type === 'red' ? 'bg-red-50 text-red-600' : 
                'bg-green-50 text-green-600'
              }`}>
                {confirmConfig.type === 'blue' ? <CheckCircle2 className="h-10 w-10" /> : 
                 confirmConfig.type === 'red' ? <XCircle className="h-10 w-10" /> : 
                 <CheckCircle className="h-10 w-10" />}
              </div>
              <div className="space-y-2">
                <h3 className="text-xl font-bold text-slate-800">{confirmConfig.title}</h3>
                <p className="text-slate-500 text-sm">{confirmConfig.message}</p>
              </div>
            </div>
            <div className="p-4 bg-slate-50 border-t border-slate-100 flex justify-center gap-3">
              <button 
                onClick={() => setIsConfirmModalOpen(false)}
                className="px-6 py-2 rounded-lg border border-slate-200 text-slate-600 font-bold text-sm hover:bg-white transition-all flex items-center gap-2"
              >
                <X className="h-4 w-4" /> Cancelar
              </button>
              <button 
                onClick={confirmConfig.onConfirm}
                className={`px-8 py-2 rounded-lg text-white font-bold text-sm shadow-md transition-all flex items-center gap-2 ${
                  confirmConfig.type === 'blue' ? 'bg-blue-600 hover:bg-blue-700 shadow-blue-200' : 
                  confirmConfig.type === 'red' ? 'bg-red-600 hover:bg-red-700 shadow-red-200' : 
                  'bg-green-600 hover:bg-green-700 shadow-green-200'
                }`}
              >
                <CheckCircle className="h-4 w-4" /> Confirmar
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

export default CFCSchedulingCenter;
