import { pgTable, text, boolean, integer, timestamp, jsonb } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  login: text('login').notNull().unique(),
  password: text('password'),
  role: text('role').notNull(),
  schoolId: text('school_id'),
  examinerId: text('examiner_id'),
  instructorId: text('instructor_id'),
  forcePasswordChange: boolean('force_password_change').default(true),
  allowedModules: jsonb('allowed_modules').$type<string[]>().default([]),
  allowedLocationIds: jsonb('allowed_location_ids').$type<string[]>().default([]),
  email: text('email'),
  phone: text('phone'),
  twoFactorEnabled: boolean('two_factor_enabled').default(false),
  createdAt: timestamp('created_at').defaultNow(),
});

export const otpCodes = pgTable('otp_codes', {
  id: text('id').primaryKey(),
  userId: text('user_id').notNull(),
  code: text('code').notNull(),        // SHA-256 hash do código real
  expiresAt: timestamp('expires_at').notNull(),
  used: boolean('used').default(false),
  failedAttempts: integer('failed_attempts').default(0),
  createdAt: timestamp('created_at').defaultNow(),
});

export const drivingSchools = pgTable('driving_schools', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  phone: text('phone'),
  email: text('email'),
  address: text('address'),
  city: text('city'),
  services: jsonb('services').$type<string[]>().default([]),
  motoYardAddress: text('moto_yard_address'),
  carYardAddress: text('car_yard_address'),
  categoryChangeYardAddress: text('category_change_yard_address'),
  mainSchedule: jsonb('main_schedule').$type<any>(),
  provisionalSchedule: jsonb('provisional_schedule').$type<any>(),
  createdAt: timestamp('created_at').defaultNow(),
});

export const examiners = pgTable('examiners', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  registrationNumber: text('registration_number').notNull(),
  canExamCommon: boolean('can_exam_common').default(true),
  canExamPCD: boolean('can_exam_pcd').default(false),
  categories: jsonb('categories').$type<string[]>().default([]),
  defaultMaxSlotsA: integer('default_max_slots_a'),
  defaultMaxSlotsB: integer('default_max_slots_b'),
  defaultMaxSlotsMudanca: integer('default_max_slots_mudanca'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const instructors = pgTable('instructors', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  cpf: text('cpf').notNull(),

  phone: text('phone'),
  category: text('category'),
  plate: text('plate'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const vehicles = pgTable('vehicles', {
  id: text('id').primaryKey(),
  instructorId: text('instructor_id').notNull(),
  type: text('type').notNull(),
  brand: text('brand').notNull(),
  model: text('model').notNull(),
  plate: text('plate').notNull(),
  active: boolean('active').default(true),
  transmission: text('transmission'),
  accessories: jsonb('accessories').$type<string[]>().default([]),
  duploComando: boolean('duplo_comando').default(false),
  procuracao: boolean('procuracao').default(false),
  createdAt: timestamp('created_at').defaultNow(),
});

export const examLocations = pgTable('exam_locations', {
  id: text('id').primaryKey(),
  cityId: text('city_id').notNull(),
  address: text('address'),
  mapsUrl: text('maps_url'),
  regionsServed: jsonb('regions_served').$type<string[]>().default([]),
  createdAt: timestamp('created_at').defaultNow(),
});

export const examSchedules = pgTable('exam_schedules', {
  id: text('id').primaryKey(),
  code: text('code').unique(),
  date: text('date').notNull(),
  time: text('time').notNull(),
  examinerIds: jsonb('examiner_ids').$type<string[]>().default([]),
  maxSlotsA: integer('max_slots_a').default(10),
  maxSlotsB: integer('max_slots_b').default(10),
  type: text('type').notNull(),
  status: text('status').notNull(),
  cancellationReason: text('cancellation_reason'),
  locationId: text('location_id'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const examRequests = pgTable('exam_requests', {
  id: text('id').primaryKey(),
  studentName: text('student_name'),
  socialName: text('social_name'),
  cpf: text('cpf'),

  phone: text('phone'),
  email: text('email'),
  address: text('address'),
  city: text('city'),
  requestType: text('request_type').default('EXTRA'),
  examType: text('exam_type').notNull(),
  intendedCategory: text('intended_category').default('B'),
  source: text('source').notNull(),
  schoolId: text('school_id'),
  paidFee: boolean('paid_fee').default(false),
  completedPracticalCourse: boolean('completed_practical_course').default(false),
  practicalHours: integer('practical_hours').default(0),
  hasVehicle: boolean('has_vehicle').default(false),
  cnhRestriction: text('cnh_restriction'),
  instructor: text('instructor'),
  vehiclePlate: text('vehicle_plate'),
  semDuploComando: boolean('sem_duplo_comando').default(false),
  checklistVehicle: boolean('checklist_vehicle').default(false),
  practicalCourseInserted: boolean('practical_course_inserted').default(false),
  taxaPaga: boolean('taxa_paga').default(false),
  disabilityType: text('disability_type'),
  specialNeeds: text('special_needs'),
  status: text('status').notNull(),
  result: text('result'),
  scheduleId: text('schedule_id'),
  scheduledDate: text('scheduled_date'),
  scheduledTime: text('scheduled_time'),
  scheduledCategory: text('scheduled_category'),
  examinerId: text('examiner_id'),
  attendanceConfirmed: boolean('attendance_confirmed').default(false),
  cancellationReason: text('cancellation_reason'),
  observation: text('observation'),
  categoryQuantities: jsonb('category_quantities').$type<Record<string, number>>(),
  examHistory: jsonb('exam_history').default([]),
  modulo: text('modulo'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  queueUpdatedAt: timestamp('queue_updated_at'),
  scheduledBy: text('scheduled_by'),
});

export const systemSettings = pgTable('system_settings', {
  id: integer('id').primaryKey().default(1),
  agencyName: text('agency_name').default('DETRAN'),
  agencyAddress: text('agency_address'),
  logoUrl: text('logo_url'),
  maintenanceMode: boolean('maintenance_mode').default(false),
  minDaysForScheduling: integer('min_days_scheduling').default(2),
  maxDailySlots: integer('max_daily_slots').default(50),
  defaultMaxSlotsA: integer('default_max_slots_a').default(10),
  defaultMaxSlotsB: integer('default_max_slots_b').default(10),
  defaultMaxSlotsMudanca: integer('default_max_slots_mudanca').default(10),
  whatsappMessageTemplate: text('whatsapp_template'),
  cfcWhatsappMessageTemplate: text('cfc_whatsapp_template'),
  defaultExamAddress: text('default_exam_address'),
  defaultExamAddressLink: text('default_exam_address_link'),
  restrictions: jsonb('restrictions').default([]),
  pcdExamName: text('pcd_exam_name'),
  pcdDefaultExamAddress: text('pcd_default_exam_address'),
  pcdDefaultExamAddressLink: text('pcd_default_exam_address_link'),
  pcdMainSchedule: jsonb('pcd_main_schedule'),
  cnhBrasilMainSchedule: jsonb('cnh_brasil_main_schedule'),
  blockWeekends: boolean('block_weekends').default(false),
  riskAreaKey: text('risk_area_key'),
});

export const auditLogs = pgTable('audit_logs', {
  id: text('id').primaryKey(),
  userId: text('user_id'),
  userName: text('user_name'),
  userRole: text('user_role'),
  action: text('action').notNull(),
  entity: text('entity').notNull(),
  entityId: text('entity_id'),
  details: jsonb('details').$type<any>(),
  createdAt: timestamp('created_at').defaultNow(),
});

export const blockedDates = pgTable('blocked_dates', {
  id: text('id').primaryKey(),
  date: text('date').notNull(),
  description: text('description'),
  isHoliday: boolean('is_holiday').default(false),
  createdAt: timestamp('created_at').defaultNow(),
});

export const cities = pgTable('cities', {
  id: text('id').primaryKey(),
  name: text('name').notNull().unique(),
  createdAt: timestamp('created_at').defaultNow(),
});

export const examScheduleSlots = pgTable('exam_schedule_slots', {
  id: text('id').primaryKey(),
  schoolId: text('school_id').notNull(),
  examType: text('exam_type').notNull(),
  requestType: text('request_type').notNull(),
  intendedCategory: text('intended_category'),
  scheduledDate: text('scheduled_date'),
  scheduledTime: text('scheduled_time'),
  examinerId: text('examiner_id'),
  scheduleId: text('schedule_id'),
  scheduledCategory: text('scheduled_category'),
  status: text('status').notNull().default('SCHEDULED'),
  attendanceConfirmed: boolean('attendance_confirmed').default(false),
  cancellationReason: text('cancellation_reason'),
  observation: text('observation'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const bancaResults = pgTable('banca_results', {
  id: text('id').primaryKey(),
  scheduleId: text('schedule_id').notNull(),
  schoolId: text('school_id').notNull(),
  category: text('category').notNull(),
  totalSlots: integer('total_slots').default(0),
  usedSlots: integer('used_slots').default(0),
  approved: integer('approved').default(0),
  failed: integer('failed').default(0),
  absent: integer('absent').default(0),
  cancelled: integer('cancelled').default(0),
  modulo: text('modulo'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// ─── Tabelas separadas por módulo ─────────────────────────────────────────────
// Mesma estrutura de exam_requests; cada tabela armazena apenas um módulo.
// O campo modulo é mantido para compatibilidade com o frontend.

export const cnhbrasilRequests = pgTable('cnhbrasil_requests', {
  id: text('id').primaryKey(),
  studentName: text('student_name'),
  socialName: text('social_name'),
  cpf: text('cpf'),
  phone: text('phone'),
  email: text('email'),
  address: text('address'),
  city: text('city'),
  requestType: text('request_type').default('EXTRA'),
  examType: text('exam_type').notNull(),
  intendedCategory: text('intended_category').default('B'),
  source: text('source').notNull(),
  schoolId: text('school_id'),
  paidFee: boolean('paid_fee').default(false),
  completedPracticalCourse: boolean('completed_practical_course').default(false),
  practicalHours: integer('practical_hours').default(0),
  hasVehicle: boolean('has_vehicle').default(false),
  cnhRestriction: text('cnh_restriction'),
  instructor: text('instructor'),
  vehiclePlate: text('vehicle_plate'),
  checklistVehicle: boolean('checklist_vehicle').default(false),
  practicalCourseInserted: boolean('practical_course_inserted').default(false),
  taxaPaga: boolean('taxa_paga').default(false),
  status: text('status').notNull(),
  result: text('result'),
  scheduleId: text('schedule_id'),
  scheduledDate: text('scheduled_date'),
  scheduledTime: text('scheduled_time'),
  scheduledCategory: text('scheduled_category'),
  examinerId: text('examiner_id'),
  attendanceConfirmed: boolean('attendance_confirmed').default(false),
  cancellationReason: text('cancellation_reason'),
  observation: text('observation'),
  examHistory: jsonb('exam_history').default([]),
  modulo: text('modulo'),
  rowColor: text('row_color'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  queueUpdatedAt: timestamp('queue_updated_at'),
  scheduledBy: text('scheduled_by'),
});

export const cfcRequests = pgTable('cfc_requests', {
  id: text('id').primaryKey(),
  studentName: text('student_name'),
  socialName: text('social_name'),
  cpf: text('cpf'),
  phone: text('phone'),
  email: text('email'),
  address: text('address'),
  city: text('city'),
  requestType: text('request_type').default('EXTRA'),
  examType: text('exam_type').notNull(),
  intendedCategory: text('intended_category').default('B'),
  source: text('source').notNull(),
  schoolId: text('school_id'),
  paidFee: boolean('paid_fee').default(false),
  completedPracticalCourse: boolean('completed_practical_course').default(false),
  practicalHours: integer('practical_hours').default(0),
  hasVehicle: boolean('has_vehicle').default(false),
  cnhRestriction: text('cnh_restriction'),
  instructor: text('instructor'),
  vehiclePlate: text('vehicle_plate'),
  semDuploComando: boolean('sem_duplo_comando').default(false),
  checklistVehicle: boolean('checklist_vehicle').default(false),
  practicalCourseInserted: boolean('practical_course_inserted').default(false),
  taxaPaga: boolean('taxa_paga').default(false),
  status: text('status').notNull(),
  result: text('result'),
  scheduleId: text('schedule_id'),
  scheduledDate: text('scheduled_date'),
  scheduledTime: text('scheduled_time'),
  scheduledCategory: text('scheduled_category'),
  examinerId: text('examiner_id'),
  attendanceConfirmed: boolean('attendance_confirmed').default(false),
  cancellationReason: text('cancellation_reason'),
  observation: text('observation'),
  categoryQuantities: jsonb('category_quantities').$type<Record<string, number>>(),
  examHistory: jsonb('exam_history').default([]),
  modulo: text('modulo'),
  rowColor: text('row_color'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  queueUpdatedAt: timestamp('queue_updated_at'),
  scheduledBy: text('scheduled_by'),
});

export const pcdRequests = pgTable('pcd_requests', {
  id: text('id').primaryKey(),
  studentName: text('student_name'),
  socialName: text('social_name'),
  cpf: text('cpf'),
  phone: text('phone'),
  email: text('email'),
  address: text('address'),
  city: text('city'),
  requestType: text('request_type').default('EXTRA'),
  examType: text('exam_type').notNull(),
  intendedCategory: text('intended_category').default('B'),
  source: text('source').notNull(),
  schoolId: text('school_id'),
  paidFee: boolean('paid_fee').default(false),
  completedPracticalCourse: boolean('completed_practical_course').default(false),
  practicalHours: integer('practical_hours').default(0),
  hasVehicle: boolean('has_vehicle').default(false),
  cnhRestriction: text('cnh_restriction'),
  instructor: text('instructor'),
  vehiclePlate: text('vehicle_plate'),
  checklistVehicle: boolean('checklist_vehicle').default(false),
  practicalCourseInserted: boolean('practical_course_inserted').default(false),
  taxaPaga: boolean('taxa_paga').default(false),
  disabilityType: text('disability_type'),
  specialNeeds: text('special_needs'),
  status: text('status').notNull(),
  result: text('result'),
  scheduleId: text('schedule_id'),
  scheduledDate: text('scheduled_date'),
  scheduledTime: text('scheduled_time'),
  scheduledCategory: text('scheduled_category'),
  examinerId: text('examiner_id'),
  attendanceConfirmed: boolean('attendance_confirmed').default(false),
  cancellationReason: text('cancellation_reason'),
  observation: text('observation'),
  examHistory: jsonb('exam_history').default([]),
  modulo: text('modulo'),
  rowColor: text('row_color'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  queueUpdatedAt: timestamp('queue_updated_at'),
  scheduledBy: text('scheduled_by'),
});

// ─── Slots de banca por módulo ────────────────────────────────────────────────
// CNH Brasil agenda direto em cnhbrasil_requests.scheduleId; não usa slots.

export const cfcScheduleSlots = pgTable('cfc_schedule_slots', {
  id: text('id').primaryKey(),
  schoolId: text('school_id').notNull(),
  examType: text('exam_type').notNull(),
  requestType: text('request_type').notNull(),
  intendedCategory: text('intended_category'),
  scheduledDate: text('scheduled_date'),
  scheduledTime: text('scheduled_time'),
  examinerId: text('examiner_id'),
  scheduleId: text('schedule_id'),
  scheduledCategory: text('scheduled_category'),
  status: text('status').notNull().default('SCHEDULED'),
  attendanceConfirmed: boolean('attendance_confirmed').default(false),
  cancellationReason: text('cancellation_reason'),
  observation: text('observation'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const pcdScheduleSlots = pgTable('pcd_schedule_slots', {
  id: text('id').primaryKey(),
  schoolId: text('school_id').notNull(),
  examType: text('exam_type').notNull(),
  requestType: text('request_type').notNull(),
  intendedCategory: text('intended_category'),
  scheduledDate: text('scheduled_date'),
  scheduledTime: text('scheduled_time'),
  examinerId: text('examiner_id'),
  scheduleId: text('schedule_id'),
  scheduledCategory: text('scheduled_category'),
  status: text('status').notNull().default('SCHEDULED'),
  attendanceConfirmed: boolean('attendance_confirmed').default(false),
  cancellationReason: text('cancellation_reason'),
  observation: text('observation'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});
